// PM Copilot — seed data (photo/video gear domain)
window.PMC_DATA = {
  user: { name: "Graham", role: "管理员", initials: "GR" },

  products: [
    {
      id: "p1",
      emoji: "💡",
      name: "Godox SL60W II 白光 LED 影视灯",
      category: "灯光",
      tags: ["持续光", "白光", "性价比"],
      status: "跟踪中",
      ai_summary: "主打高性价比白光 LED 影视灯，色温 5600K，功率 60W，配 Bowens 卡口。亚马逊与淘宝双渠道布局，差评集中在散热风扇噪音和遥控器配对。",
      selling_points: ["色温 5600K", "Bowens 卡口", "60W 等效 200W", "无频闪"],
      negative_keywords: ["风扇噪音大", "遥控失灵", "灯泡寿命短"],
      synced_at: "2026-05-09 23:08",
      platforms: [
        { platform: "amazon", url: "amazon.com/dp/B07K84YW86", price: "$89.99", cost: "¥280", rating: 4.6, reviews: 3842, sales: "1.2k+/月" },
        { platform: "taobao", url: "taobao.com/item/684931", price: "¥598", cost: "¥280", rating: 4.8, reviews: 1280, sales: "890+/月" },
      ],
    },
    {
      id: "p2",
      emoji: "🔦",
      name: "Neewer 660 PRO II 双色温 LED 灯板",
      category: "灯光",
      tags: ["平板灯", "双色温"],
      status: "跟踪中",
      ai_summary: "Neewer 主打入门级双色温 LED 平板灯，3200–5600K，含遥控与电池支架。色彩还原 CRI 97。",
      selling_points: ["CRI 97+", "电池供电", "便携支架", "遥控控光"],
      negative_keywords: ["支架易松动", "充电缓慢"],
      synced_at: "2026-05-09 23:08",
      platforms: [
        { platform: "amazon", url: "amazon.com/dp/B08KH4G2Q1", price: "$79.99", cost: "¥240", rating: 4.4, reviews: 2156, sales: "950+/月" },
      ],
    },
    {
      id: "p3",
      emoji: "📸",
      name: "神牛 AD200Pro 口袋外拍闪光灯",
      category: "灯光",
      tags: ["闪光灯", "外拍", "TTL"],
      status: "跟踪中",
      ai_summary: "口袋型 200Ws 外拍灯标杆产品，可换灯头，支持 TTL/HSS。淘宝主战场，复购率高。",
      selling_points: ["200Ws 输出", "可换灯头", "HSS 1/8000s", "锂电池"],
      negative_keywords: ["回电稍慢", "原装包易磨"],
      synced_at: "2026-05-09 23:08",
      platforms: [
        { platform: "taobao", url: "taobao.com/item/591824", price: "¥1,580", cost: "¥780", rating: 4.8, reviews: 3120, sales: "320+/月" },
        { platform: "jd",     url: "item.jd.com/100012345.html", price: "¥1,599", cost: "¥780", rating: 4.9, reviews: 980, sales: "180+/月" },
      ],
    },
    {
      id: "p4",
      emoji: "🎥",
      name: "DJI RS 3 Mini 单手稳定器",
      category: "稳定器",
      tags: ["手持云台", "微单适配"],
      status: "跟踪中",
      ai_summary: "DJI 入门款微单稳定器,主打单手轻量。负载 2kg,适配主流微单。差评集中在卡口适配以及 APP 校准。",
      selling_points: ["2kg 负载", "单手操控", "纵拍模式", "原生竖拍"],
      negative_keywords: ["APP 校准复杂", "电量显示不准"],
      synced_at: "2026-05-09 22:15",
      platforms: [
        { platform: "amazon", url: "amazon.com/dp/B0BL2BMHF1", price: "$179", cost: "¥820", rating: 4.7, reviews: 1245, sales: "560+/月" },
        { platform: "jd",     url: "item.jd.com/100050001.html", price: "¥1,499", cost: "¥820", rating: 4.8, reviews: 2180, sales: "420+/月" },
      ],
    },
    {
      id: "p5",
      emoji: "📷",
      name: "Ulanzi MT-44 桌面三脚架",
      category: "三脚架",
      tags: ["桌面", "可延伸"],
      status: "新录入",
      ai_summary: "面向 Vlog 与桌面拍摄的可伸缩三脚架,1.7m 最高,折叠 42cm。京东主推国内市场。",
      selling_points: ["1.7m 最高", "折叠 42cm", "云台快装板", "重量 480g"],
      negative_keywords: ["腿管略晃", "扣环易磨"],
      synced_at: null,
      platforms: [
        { platform: "jd", url: "item.jd.com/100089012.html", price: "¥299", cost: "¥95", rating: 4.5, reviews: 5800, sales: "2.1k+/月" },
      ],
    },
    {
      id: "p6",
      emoji: "🔭",
      name: "Sigma 16mm F1.4 DC DN 定焦镜头",
      category: "镜头",
      tags: ["APS-C", "广角", "F1.4"],
      status: "跟踪中",
      ai_summary: "APS-C 画幅 16mm F1.4,适马 Contemporary 系列。Vlog 和星空摄影双场景受欢迎。",
      selling_points: ["F1.4 大光圈", "金属卡口", "9 片光圈叶片", "405g 轻量"],
      negative_keywords: ["紫边轻微", "锁紧螺丝偏松"],
      synced_at: "2026-05-09 23:08",
      platforms: [
        { platform: "amazon", url: "amazon.com/dp/B071ZJZG5Z", price: "$429", cost: "¥1,850", rating: 4.9, reviews: 2890, sales: "210+/月" },
      ],
    },
    {
      id: "p7",
      emoji: "🎤",
      name: "RØDE Wireless GO II 双通道无线麦",
      category: "麦克风",
      tags: ["无线麦", "双通道"],
      status: "跟踪中",
      ai_summary: "无线麦克风类目领头产品,双通道,内置存储,7 小时续航。亚马逊月销稳定。",
      selling_points: ["双通道", "内置 40h 录音", "200m 射程", "USB-C 充电"],
      negative_keywords: ["夹子塑料感", "iPhone 适配线另购"],
      synced_at: "2026-05-09 23:08",
      platforms: [
        { platform: "amazon", url: "amazon.com/dp/B095PVPMTX", price: "$299", cost: "¥1,120", rating: 4.7, reviews: 8920, sales: "1.5k+/月" },
      ],
    },
    {
      id: "p8",
      emoji: "🪞",
      name: "Aputure Amaran COB 60d S 聚光灯",
      category: "灯光",
      tags: ["聚光灯", "Bowens", "高显色"],
      status: "新录入",
      ai_summary: "Aputure 旗下 Amaran 系列入门聚光灯,65W,Bowens 卡口。Kickstarter 早鸟反馈良好。",
      selling_points: ["65W 输出", "TLCI 96+", "蓝牙控制", "静音模式"],
      negative_keywords: ["遥控偶尔丢失", "包装较简陋"],
      synced_at: null,
      platforms: [
        { platform: "kickstarter", url: "kickstarter.com/projects/aputure/amaran-60d", price: "$199", cost: "¥780", rating: 4.6, reviews: 412, sales: "众筹中" },
      ],
    },
  ],

  demands: [
    {
      id: "d1", title: "磁吸快拆补光灯创意方案",
      thumbHue: 30,
      summary: "博主自制磁吸接口的 RGB 补光灯,可吸附在相机机顶或冰箱上,主打 Vlog 即拍即用。配文获得 8k+ 收藏。",
      source: "xiaohongshu", date: "2026-05-08",
      innovation: "形态创新",
      scenarios: ["Vlog/自拍", "桌面俯拍"],
      painpoints: ["安装固定麻烦", "携带不便/太重"],
    },
    {
      id: "d2", title: "AI 跟拍三脚架(Pivo Tracker 概念升级)",
      thumbHue: 200,
      summary: "Kickstarter 项目,内置视觉算法的电动三脚架,识别人脸自动旋转跟随。早鸟价 $299,众筹完成度 642%。",
      source: "kickstarter", date: "2026-05-07",
      innovation: "技术创新",
      scenarios: ["户外旅拍", "运动/极限拍摄"],
      painpoints: ["防抖不足", "操作复杂/学习成本高"],
    },
    {
      id: "d3", title: "便携直播灯+反光板套装", thumbHue: 320,
      summary: "Instagram 创作者展示自购搭配:Aputure mini 灯+折叠反光板+桌面臂,总价 $250 解决直播打光痛点。",
      source: "instagram", date: "2026-05-06",
      innovation: "性价比创新",
      scenarios: ["直播/带货", "桌面俯拍"],
      painpoints: ["价格过高/性价比低", "配件缺失/需另购"],
    },
    {
      id: "d4", title: "运动相机磁吸胸戴方案", thumbHue: 110,
      summary: "GoPro 用户分享自制磁吸胸戴,登山场景下避免传统绑带摩擦。评论区高频提到希望厂商出官方版。",
      source: "youtube", date: "2026-05-05",
      innovation: "使用方式创新",
      scenarios: ["户外旅拍", "运动/极限拍摄"],
      painpoints: ["安装固定麻烦", "携带不便/太重"],
    },
    {
      id: "d5", title: "USB-C 一拖三补光灯组", thumbHue: 250,
      summary: "小红书创作者将三盏 RGB 灯通过 USB-C 串联接入笔记本,免插座免遥控。1.2k 点赞。",
      source: "xiaohongshu", date: "2026-05-05",
      innovation: "生态整合",
      scenarios: ["桌面俯拍", "教育/网课"],
      painpoints: ["配件缺失/需另购", "无线连接不稳定"],
    },
    {
      id: "d6", title: "可拆解模块化云台概念", thumbHue: 60,
      summary: "Kickstarter:云台手柄/平衡环/电池可独立购买,旅行携带时拆分体积减半。",
      source: "kickstarter", date: "2026-05-04",
      innovation: "形态创新",
      scenarios: ["户外旅拍"],
      painpoints: ["携带不便/太重", "收纳困难"],
    },
    {
      id: "d7", title: "美食桌面俯拍小臂套装", thumbHue: 15,
      summary: "Vlogger 介绍自己的美食拍摄装备,重点是 60cm 小臂+磁吸顶补光,桌面适用。",
      source: "youtube", date: "2026-05-03",
      innovation: "场景拓展",
      scenarios: ["桌面俯拍", "短视频创作"],
      painpoints: ["安装固定麻烦"],
    },
    {
      id: "d8", title: "演唱会便携稳定补光夹", thumbHue: 290,
      summary: "Instagram 用户夜场拍摄技巧分享:夹在手机上的补光+便携三脚架,演唱会环境下出片率提升明显。",
      source: "instagram", date: "2026-05-02",
      innovation: "场景拓展",
      scenarios: ["运动/极限拍摄", "短视频创作"],
      painpoints: ["画质不够(暗光/噪点)", "防抖不足"],
    },
    {
      id: "d9", title: "RGB 棒灯创意拍摄技巧合集", thumbHue: 340,
      summary: "PetaPixel 整理 12 种 RGB 棒灯使用场景,人像、产品、慢门。流量爆款。",
      source: "youtube", date: "2026-05-01",
      innovation: "使用方式创新",
      scenarios: ["室内棚拍", "产品摄影"],
      painpoints: ["调光/调色不精准"],
    },
  ],

  news: [
    {
      id: "n1", date: "2026-05-10", time: "2小时前",
      titleZh: "DJI 发布 Osmo Pocket 4,搭载 1 英寸 CMOS 与 8K 视频",
      summary: "DJI 旗下口袋云台相机迭代至第四代,主摄升级到 1 英寸,新增 8K/30fps 视频录制能力,售价 4,999 元起。",
      type: "新品发布", source: "DJI Blog", thumbHue: 220, unread: true, starred: false,
    },
    {
      id: "n2", date: "2026-05-10", time: "5小时前",
      titleZh: "PetaPixel 2026 摄影器材趋势报告:AI 辅助拍摄成主流方向",
      summary: "报告指出超半数受访摄影师在 2026 年使用 AI 辅助构图、对焦或后期工具,微单+计算摄影的融合是大势所趋。",
      type: "行业趋势", source: "PetaPixel", thumbHue: 30, unread: true, starred: true,
    },
    {
      id: "n3", date: "2026-05-10", time: "9小时前",
      titleZh: "Insta360 推出 X5 Pro,新增激光雷达辅助对焦",
      summary: "Insta360 全景相机更新至 X5 Pro,首次引入 LiDAR 模块,在低光环境下对焦速度提升 3 倍。",
      type: "新品发布", source: "Insta360 News", thumbHue: 150, unread: false, starred: false,
    },
    {
      id: "n4", date: "2026-05-09", time: "昨天",
      titleZh: "Sony α7C III 即将发布,定位轻量全画幅入门",
      summary: "Sony 全幅微单 α7C III 谍照流出,重量降至 480g,搭载 33MP 全画幅传感器,直接对标 Lumix S9。",
      type: "新品发布", source: "DPReview", thumbHue: 280, unread: false, starred: false,
    },
    {
      id: "n5", date: "2026-05-09", time: "昨天",
      titleZh: "Godox 推出全新 V100 闪光灯,内置 AI 测光",
      summary: "Godox V100 是首款搭载 AI 测光算法的闪光灯,可根据场景自动调整输出与色温,售价 ¥2,499。",
      type: "新品发布", source: "Godox 官网", thumbHue: 60, unread: false, starred: true,
    },
    {
      id: "n6", date: "2026-05-08", time: "2 天前",
      titleZh: "短视频平台创作者偏好调研:补光灯成为入门第二件设备",
      summary: "针对 5,000 名创作者的调研显示,补光灯位列入门必买设备第二位,仅次于三脚架。RGB 灯需求增长 47%。",
      type: "行业趋势", source: "Vlog 创业研究", thumbHue: 340, unread: false, starred: false,
    },
    {
      id: "n7", date: "2026-05-08", time: "2 天前",
      titleZh: "Aputure 发布 Light Storm 1200d Pro 影视灯",
      summary: "Aputure LS 1200d Pro 全新散热结构,功率 1200W,主打高端影视棚级用户,售价 $5,499。",
      type: "新品发布", source: "Aputure", thumbHue: 200, unread: false, starred: false,
    },
  ],

  research: [
    {
      id: "r1", title: "便携双色温补光灯 Pro",
      desc: "一款 65W 便携双色温补光灯,主打轻量(<1kg)+高显色(CRI 97+),定价 $99-129 区间,瞄准 Vlog 与桌面创作者。差异化点:磁吸快拆+电池供电+APP 一键场景预设。",
      status: "已完成", date: "2026-05-09",
      products: ["p1", "p2", "p8"],
      demands: ["d1", "d3", "d5"],
      analysis: [
        { title: "竞品格局", icon: "📊", confidence: 0.85,
          text: "$80–100 价位段是双色温平板/聚光灯竞争最激烈的区间。Godox SL60W II($89.99,4.6★/3842 评)与 Neewer 660 PRO II($79.99,4.4★/2156 评)占据用户心智,但二者均为传统支架式,缺乏便携形态;Aputure Amaran 60d S(Kickstarter,$199)以聚光形态切入但价格更高。",
          source: "Godox SL60W II / Neewer 660 PRO II / Aputure Amaran 60d S" },
        { title: "差异化机会", icon: "💡", confidence: 0.72,
          text: "用户痛点集中在「配件缺失/需另购」(3 条需求记录)与「散热噪音」(2 条竞品差评)。便携磁吸结构 + 内置电池 + APP 场景预设这一组合在现有 SKU 中尚无完整覆盖,可形成第一道差异化。",
          source: "需求记录 d1/d3/d5 · Godox/Neewer 差评" },
        { title: "定价建议", icon: "💰", confidence: 0.78,
          text: "建议零售价 $99–129 区间。$99 锚定 Godox SL60W,以「便携+磁吸+电池」做溢价支撑;$129 上探 Aputure 价格带但保留性价比心智。建议早鸟价 $79 起。",
          source: "竞品价格分布 + 类目均价" },
        { title: "风险提示", icon: "⚠️", confidence: 0.66,
          text: "电池供电产品在跨境物流(锂电池)与认证(UL/CE/PSE)上存在 4–6 周额外周期。Bowens 卡口生态依赖现有配件商,需要在产品定义阶段决定兼容性策略。",
          source: "类目跨境物流经验 + 行业认证流程" },
      ],
    },
    {
      id: "r2", title: "磁吸快拆三脚架",
      desc: "面向户外旅拍的 1.6m 三脚架,主打磁吸快拆云台,目标价 ¥499 区间。",
      status: "分析中", date: "2026-05-08",
      products: ["p4", "p5"], demands: ["d4", "d6", "d7"],
    },
    {
      id: "r3", title: "Creator Kit 套装方案",
      desc: "Vlog 入门套装,包含轻量补光+无线麦+迷你三脚架,目标价 $399。",
      status: "草稿", date: "2026-05-07",
      products: [], demands: [],
    },
  ],

  rssSources: [
    { id: "s1", name: "DJI Official Blog", url: "https://www.dji.com/cn/newsroom/rss.xml", interval: 60, active: true },
    { id: "s2", name: "PetaPixel", url: "https://petapixel.com/feed/", interval: 120, active: true },
    { id: "s3", name: "Insta360 News", url: "https://blog.insta360.com/feed", interval: 60, active: false },
    { id: "s4", name: "DPReview", url: "https://dpreview.com/feeds/news.xml", interval: 120, active: true },
    { id: "s5", name: "Aputure 官网", url: "https://aputure.com/blog/feed/", interval: 240, active: true },
  ],
};
